[WIP] service large withdrawals
igneous-labs/stake-pool-sdk pull request #36
Opened 2022-02-16 08:09 UTC by billythedummy

Closes #18 

Need to setup localnet validators to test

2022-03-01 07:44 UTC, f8122dac91 commented on src/stake-pool/instructions.ts
> + * @param dropletsToUnstake: number of droplets to withdraw
very nice

2022-03-01 07:48 UTC, Johnnycus approved these changes

2022-03-01 07:54 UTC, f8122dac91 commented
Nice! The client facing APIs are coming along nicely I think. Changes are pretty significant, will take some time to fully review this tho.

Also it looks like the two test cases have failed with `WithdrawalUnserviceableError` thrown.

2022-03-02 08:21 UTC, f8122dac91 requested changes
Issues are just adding doc comments for two exported types

2022-03-02 08:21 UTC, f8122dac91 commented on src/stake-pool/utils.ts
> +export type WithdrawalReceipt = {
maybe a doc comment heading for typedoc?

2022-03-02 08:21 UTC, f8122dac91 commented on src/stake-pool/utils.ts
> +export type ValidatorWithdrawalReceipt = {
maybe a doc comment heading for typedoc?

2022-03-03 02:17 UTC, billythedummy commented on src/socean.ts
>  export class Socean {
nah i think its fine to stick to testnet for now, devnet stake pool needs a few more epochs to be ready

2022-03-03 02:20 UTC, f8122dac91 approved these changes

2022-03-03 02:20 UTC, f8122dac91 commented
All green!

2022-03-03 03:33 UTC, billythedummy commented
```
 Transaction simulation failed: Error processing Instruction 0: Program failed to complete 
    Program 5ocnV1qiCgaQR8Jb8xWnVbApfaygJ8tNoZfgPwsgx9kx invoke [1]
    Program log: Instruction: UpdateValidatorListBalance
    Program 5ocnV1qiCgaQR8Jb8xWnVbApfaygJ8tNoZfgPwsgx9kx consumed 20326 of 200000 compute units
    Program failed to complete: Access violation in stack frame 1 at address 0x200001ee0 of size 8 by instruction #12425
    Program 5ocnV1qiCgaQR8Jb8xWnVbApfaygJ8tNoZfgPwsgx9kx failed: Program failed to complete
```

well this is new. Wait I think I've seen this error somewhere before

2022-03-03 04:47 UTC, Johnnycus commented
> ```
>  Transaction simulation failed: Error processing Instruction 0: Program failed to complete 
>     Program 5ocnV1qiCgaQR8Jb8xWnVbApfaygJ8tNoZfgPwsgx9kx invoke [1]
>     Program log: Instruction: UpdateValidatorListBalance
>     Program 5ocnV1qiCgaQR8Jb8xWnVbApfaygJ8tNoZfgPwsgx9kx consumed 20326 of 200000 compute units
>     Program failed to complete: Access violation in stack frame 1 at address 0x200001ee0 of size 8 by instruction #12425
>     Program 5ocnV1qiCgaQR8Jb8xWnVbApfaygJ8tNoZfgPwsgx9kx failed: Program failed to complete
> ```
> 
> well this is new. Wait I think I've seen this error somewhere before

In `yarn test`? I had this a couple of times, once I had 3 failed tests, then 2, then all passed

2022-03-03 05:53 UTC, billythedummy commented
Yeah this is quite fucked up but apparently our build is incompatible with solana build tools 1.8+. I've redeployed to devnet using a 1.7.14 docker build env and it works now: https://github.com/igneous-labs/solana-program-library/commit/2aa00d2be0a018bec776090ace9c74a10086c65e.

Oh wait i realized there is a situation where the user can start withdrawing from the reserve - there is only 1 stake account (transient or main) present for all validators in the pool, lemme modify `calcWithdrawal()` and test it

2022-03-03 06:07 UTC, Johnnycus commented
> Yeah this is quite fucked up but apparently our build is incompatible with solana build tools 1.8+. I've redeployed to devnet using a 1.7.14 docker build env and it works now: [igneous-labs/solana-program-library@2aa00d2](https://github.com/igneous-labs/solana-program-library/commit/2aa00d2be0a018bec776090ace9c74a10086c65e).
> 
> ~Oh wait i realized there is a situation where the user can start withdrawing from the reserve - there is only 1 stake account (transient or main) present for all validators in the pool, lemme modify `calcWithdrawal()` and test it~ nvm, you need absolutely all stake accounts to be deleted

Downgrading fixes the issue?

2022-03-03 07:10 UTC, billythedummy commented
> > Yeah this is quite fucked up but apparently our build is incompatible with solana build tools 1.8+. I've redeployed to devnet using a 1.7.14 docker build env and it works now: [igneous-labs/solana-program-library@2aa00d2](https://github.com/igneous-labs/solana-program-library/commit/2aa00d2be0a018bec776090ace9c74a10086c65e).
> > ~Oh wait i realized there is a situation where the user can start withdrawing from the reserve - there is only 1 stake account (transient or main) present for all validators in the pool, lemme modify `calcWithdrawal()` and test it~ nvm, you need absolutely all stake accounts to be deleted
> 
> Downgrading fixes the issue?

yeah downgrading the solana on-chain program build tools. Testnet wasn't affected because it was deployed a long time ago using the old build tools

2022-03-03 08:02 UTC, merged